name: ABC
on:
  pull_request_target:
    branches:
      - master
    types:
      - opened

jobs:
  open-patch-request:
    if: |
      startsWith(github.head_ref, 'master-')
#&& github.context.payload.pull_request.user.login == 'oconnor0'
    runs-on: ubuntu-latest
    steps:
      - name: Comment with patch request.
        uses: actions/github-script@v6
        with:
          script: |
            // console.log(github)
            console.log(github.context.payload.pull_request.user.login)
            console.log(github.context.payload) //.pull_request.user.login == 'oconnor0'
            console.log('oh, hai')
